plugins:
  retrieve:
    module: geek-time-mongodb
    middleware: retrieve
    mongoDbUri: "mongodb://localhost:27017/geektime"
    includeTags: '#foo'
  loadCsv:
    module: csv
    middleware: exportFile
    file: out.csv