plugins:
  loadCsv:
    module: csv
    middleware: importFile
    file: test/testData.csv
  parseNumber: {}
  parseDate: {}
  parseTags: {}
  selectColumns:
    include:
      - date
      - description
      - blocks
  store:
    module: geek-time-mongodb
    middleware: store
    mongoDbUri: "mongodb://localhost:27017/geektime"