plugins:
  loadCsv:
    file: test/testData.csv
  parseDate: {}
  parseTags: {}
  selectColumns:
    include:
      - date
      - description
  store:
    module: geek-time-mongodb
    middleware: store
    mongoDbUri: "mongodb://localhost:27017/geektime"